// 这是protobuf的版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: protobuf/fts.proto

//定义包名

package fts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义数据结构，message 类似golang中的struct
type ActionResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err     *string            `protobuf:"bytes,1,opt,name=err,proto3,oneof" json:"err,omitempty"`    // 错误信息
	Success bool               `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Result  []*QueryResultItem `protobuf:"bytes,3,rep,name=result,proto3" json:"result,omitempty"`    // 查询结果
}

func (x *ActionResult) Reset() {
	*x = ActionResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_fts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResult) ProtoMessage() {}

func (x *ActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_fts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResult.ProtoReflect.Descriptor instead.
func (*ActionResult) Descriptor() ([]byte, []int) {
	return file_protobuf_fts_proto_rawDescGZIP(), []int{0}
}

func (x *ActionResult) GetErr() string {
	if x != nil && x.Err != nil {
		return *x.Err
	}
	return ""
}

func (x *ActionResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResult) GetResult() []*QueryResultItem {
	if x != nil {
		return x.Result
	}
	return nil
}

type QueryResultItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`        // 文档id
	Title string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`   // 文档标题
	Data  string  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`     // 文档关联的查询内容
	Score float32 `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"` // 得分
}

func (x *QueryResultItem) Reset() {
	*x = QueryResultItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_fts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResultItem) ProtoMessage() {}

func (x *QueryResultItem) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_fts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResultItem.ProtoReflect.Descriptor instead.
func (*QueryResultItem) Descriptor() ([]byte, []int) {
	return file_protobuf_fts_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResultItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QueryResultItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QueryResultItem) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *QueryResultItem) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type Contents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`      // 文档id
	Title string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"` // 文档标题
	Body  []string `protobuf:"bytes,3,rep,name=body,proto3" json:"body,omitempty"`   // 内容
}

func (x *Contents) Reset() {
	*x = Contents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_fts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contents) ProtoMessage() {}

func (x *Contents) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_fts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contents.ProtoReflect.Descriptor instead.
func (*Contents) Descriptor() ([]byte, []int) {
	return file_protobuf_fts_proto_rawDescGZIP(), []int{2}
}

func (x *Contents) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Contents) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Contents) GetBody() []string {
	if x != nil {
		return x.Body
	}
	return nil
}

type BatchContents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contents []*Contents `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"` // 内容
}

func (x *BatchContents) Reset() {
	*x = BatchContents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_fts_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchContents) ProtoMessage() {}

func (x *BatchContents) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_fts_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchContents.ProtoReflect.Descriptor instead.
func (*BatchContents) Descriptor() ([]byte, []int) {
	return file_protobuf_fts_proto_rawDescGZIP(), []int{3}
}

func (x *BatchContents) GetContents() []*Contents {
	if x != nil {
		return x.Contents
	}
	return nil
}

var File_protobuf_fts_proto protoreflect.FileDescriptor

var file_protobuf_fts_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x66, 0x74, 0x73, 0x22, 0x75, 0x0a, 0x0c, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x15, 0x0a, 0x03, 0x65, 0x72, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x65, 0x72, 0x72, 0x88, 0x01, 0x01,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2c, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x74, 0x73,
	0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x65, 0x72, 0x72,
	0x22, 0x61, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x22, 0x44, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x3a, 0x0a, 0x0d, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x29, 0x0a, 0x08, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x66,
	0x74, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x08, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x0d, 0x5a, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x73,
	0x2f, 0x66, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_fts_proto_rawDescOnce sync.Once
	file_protobuf_fts_proto_rawDescData = file_protobuf_fts_proto_rawDesc
)

func file_protobuf_fts_proto_rawDescGZIP() []byte {
	file_protobuf_fts_proto_rawDescOnce.Do(func() {
		file_protobuf_fts_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_fts_proto_rawDescData)
	})
	return file_protobuf_fts_proto_rawDescData
}

var file_protobuf_fts_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuf_fts_proto_goTypes = []interface{}{
	(*ActionResult)(nil),    // 0: fts.ActionResult
	(*QueryResultItem)(nil), // 1: fts.QueryResultItem
	(*Contents)(nil),        // 2: fts.Contents
	(*BatchContents)(nil),   // 3: fts.BatchContents
}
var file_protobuf_fts_proto_depIdxs = []int32{
	1, // 0: fts.ActionResult.result:type_name -> fts.QueryResultItem
	2, // 1: fts.BatchContents.contents:type_name -> fts.Contents
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_fts_proto_init() }
func file_protobuf_fts_proto_init() {
	if File_protobuf_fts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_fts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_fts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResultItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_fts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Contents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_fts_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchContents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuf_fts_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_fts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_fts_proto_goTypes,
		DependencyIndexes: file_protobuf_fts_proto_depIdxs,
		MessageInfos:      file_protobuf_fts_proto_msgTypes,
	}.Build()
	File_protobuf_fts_proto = out.File
	file_protobuf_fts_proto_rawDesc = nil
	file_protobuf_fts_proto_goTypes = nil
	file_protobuf_fts_proto_depIdxs = nil
}
